# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motto',
            old_name='Motto',
            new_name='text',
        ),
    ]
